[2020-02-22 21:18:31] INFO [<module>: run_all.py, 6] =====================================测试开始========================================
[2020-02-22 21:18:31] DEBUG [_new_conn: connectionpool.py, 221] Starting new HTTP connection (1): 115.28.108.130:5000
[2020-02-22 21:18:31] DEBUG [_make_request: connectionpool.py, 428] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2020-02-22 21:18:31] INFO [log_case_info: case_log.py, 7] 测试用例：test_user_login_normal
[2020-02-22 21:18:31] INFO [log_case_info: case_log.py, 8] url:http://115.28.108.130:5000/api/user/login/
[2020-02-22 21:18:31] INFO [log_case_info: case_log.py, 9] 请求参数：{"name":"范冰冰","password":"123456"}
[2020-02-22 21:18:31] INFO [log_case_info: case_log.py, 10] 期望结果：<h1>登录成功</h1>
[2020-02-22 21:18:31] INFO [log_case_info: case_log.py, 11] 实际结果：<h1>登录成功</h1>
[2020-02-22 21:18:31] DEBUG [_new_conn: connectionpool.py, 221] Starting new HTTP connection (1): 115.28.108.130:5000
[2020-02-22 21:18:31] DEBUG [_make_request: connectionpool.py, 428] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2020-02-22 21:18:31] INFO [log_case_info: case_log.py, 7] 测试用例：test_user_login_password_wrong
[2020-02-22 21:18:31] INFO [log_case_info: case_log.py, 8] url:http://115.28.108.130:5000/api/user/login/
[2020-02-22 21:18:31] INFO [log_case_info: case_log.py, 9] 请求参数：{"name": "张三","password":"1234567"}
[2020-02-22 21:18:31] INFO [log_case_info: case_log.py, 10] 期望结果：<h1>失败，用户名或密码错误</h1>
[2020-02-22 21:18:31] INFO [log_case_info: case_log.py, 11] 实际结果：<h1>失败，用户名或密码错误</h1>
[2020-02-22 21:18:31] DEBUG [query: db.py, 14] select * from EMPLOYEE where FIRST_NAME='张三'
[2020-02-22 21:18:31] ERROR [exec: db.py, 24] (1062, "Duplicate entry '' for key 'PRIMARY'")
[2020-02-22 21:18:31] DEBUG [_new_conn: connectionpool.py, 221] Starting new HTTP connection (1): 115.28.108.130:5000
[2020-02-22 21:18:31] DEBUG [_make_request: connectionpool.py, 428] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 152
[2020-02-22 21:18:31] DEBUG [query: db.py, 14] select * from EMPLOYEE where FIRST_NAME='范冰冰'
[2020-02-22 21:18:31] DEBUG [_new_conn: connectionpool.py, 221] Starting new HTTP connection (1): 115.28.108.130:5000
[2020-02-22 21:18:31] DEBUG [_make_request: connectionpool.py, 428] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 158
[2020-02-22 21:18:32] ERROR [send_email: send_email.py, 35] (535, b'Error: authentication failed')
[2020-02-22 21:18:32] INFO [<module>: run_all.py, 15] =====================================测试结束=======S=================================
[2020-02-22 21:21:39] INFO [<module>: run_all.py, 6] =====================================测试开始========================================
[2020-02-22 21:21:40] DEBUG [_new_conn: connectionpool.py, 221] Starting new HTTP connection (1): 115.28.108.130:5000
[2020-02-22 21:21:40] DEBUG [_make_request: connectionpool.py, 428] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2020-02-22 21:21:40] INFO [log_case_info: case_log.py, 7] 测试用例：test_user_login_normal
[2020-02-22 21:21:40] INFO [log_case_info: case_log.py, 8] url:http://115.28.108.130:5000/api/user/login/
[2020-02-22 21:21:40] INFO [log_case_info: case_log.py, 9] 请求参数：{"name":"范冰冰","password":"123456"}
[2020-02-22 21:21:40] INFO [log_case_info: case_log.py, 10] 期望结果：<h1>登录成功</h1>
[2020-02-22 21:21:40] INFO [log_case_info: case_log.py, 11] 实际结果：<h1>登录成功</h1>
[2020-02-22 21:21:40] DEBUG [_new_conn: connectionpool.py, 221] Starting new HTTP connection (1): 115.28.108.130:5000
[2020-02-22 21:21:40] DEBUG [_make_request: connectionpool.py, 428] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2020-02-22 21:21:40] INFO [log_case_info: case_log.py, 7] 测试用例：test_user_login_password_wrong
[2020-02-22 21:21:40] INFO [log_case_info: case_log.py, 8] url:http://115.28.108.130:5000/api/user/login/
[2020-02-22 21:21:40] INFO [log_case_info: case_log.py, 9] 请求参数：{"name": "张三","password":"1234567"}
[2020-02-22 21:21:40] INFO [log_case_info: case_log.py, 10] 期望结果：<h1>失败，用户名或密码错误</h1>
[2020-02-22 21:21:40] INFO [log_case_info: case_log.py, 11] 实际结果：<h1>失败，用户名或密码错误</h1>
[2020-02-22 21:21:40] DEBUG [query: db.py, 14] select * from EMPLOYEE where FIRST_NAME='张三'
[2020-02-22 21:21:40] ERROR [exec: db.py, 24] (1062, "Duplicate entry '' for key 'PRIMARY'")
[2020-02-22 21:21:40] DEBUG [_new_conn: connectionpool.py, 221] Starting new HTTP connection (1): 115.28.108.130:5000
[2020-02-22 21:21:40] DEBUG [_make_request: connectionpool.py, 428] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 152
[2020-02-22 21:21:40] DEBUG [query: db.py, 14] select * from EMPLOYEE where FIRST_NAME='范冰冰'
[2020-02-22 21:21:40] DEBUG [_new_conn: connectionpool.py, 221] Starting new HTTP connection (1): 115.28.108.130:5000
[2020-02-22 21:21:40] DEBUG [_make_request: connectionpool.py, 428] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 158
[2020-02-22 21:21:42] INFO [send_email: send_email.py, 33] 邮件发送完成！
[2020-02-22 21:21:42] INFO [<module>: run_all.py, 15] =====================================测试结束=======S=================================
